### ISSUE TITLE
Remove ability to add new movies which share the same id

### ISSUE THREAD

**Issue by melonrush13** [microsoft/helium#229]
Don't let users add a new movie if it shares an ID as a previously added movie.

Change old movies so we don't have any existing movies with the same id, and make sure in the future we aren't allowed to add a new one if it shares an id.

**Comment by frodopwns** [comment]
I don't think it's possible to have duplicate movies with the same ID. It is possible to POST a movie that has an ID preset and wipe out an existing movie. This is expected behavior for a PUT, but probably not for a POST. This is because we are using upsert for POSTS, but not checking for the existence of the entity by ID before upserting.

**Comment by frodopwns** [comment]
Looks like we may be able to replace `upsert` with `insert` for POSTs
